### PR TITLE
Updated vversions in requirements.txt

### PR DESCRIPTION
**Pull request by maxtacu**

### CODE REVIEW

**Comment by abitrolly** [comment]
This file is not used for installation, because all dependencies are in `setup.py`.

**Comment by maxtacu** [comment]
yes, I know, but I use it for running the app in pipenv

**Comment by maxtacu** [comment]
just wanted to have it in sync with `setup.py`

**Comment by abitrolly** [comment]
No problems with that. Guess that also helps GitHub to warn about security issues.

**Pull request merged**
